# Generated by Django 3.2.24 on 2024-02-29 10:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220527_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 10, 46, 59, 451585, tzinfo=utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 10, 46, 59, 444879, tzinfo=utc), verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='post_feedback',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 29, 10, 46, 59, 451585, tzinfo=utc), verbose_name='Posted Date'),
        ),
    ]
